### ISSUE TITLE
ckanext.spatial.common_map.subdomains not used?

### ISSUE THREAD

**Issue by mattfullerton** [ckan/ckanext-geoview#9]
I am using SSL, so with ckanext-spatial, I needed to use a custom tile server just so I could add the extra two characters in the url :)
I see SSL is now working without the custom server (brilliant!) but I'd like to keep using both extensions for a little while longer and stick with the custom server.

In any case, the problem: I've included the {s} wildcard for subdomains but it isn't getting replaced by one of the characters in ckanext.spatial.common_map.subdomains as used to happen with ckanext-spatial.

**Comment by dythya** [comment]
I found this as well.
The lastest version of OpenLayers says it you can specify the {s} as {a-d}. Assuming that your subdomains are just represented as  {a-d}-place.something replace as a-place.something, b-place.something.
But I am wondering if this is an earlier version of the OpenLayers?
I saw doc: http://openlayers.org/en/latest/apidoc/ol.source.XYZ.html

**Comment by dythya** [comment]
The version of OpenLayers looks to be a couple of years old.

Is there any work currently being done around updating the version of OpenLayers?

**Comment by pduchesne** [comment]
Well, that's a very timely question, as a beta version of the integration
with OpenLayers 4.2 is available at pduchesne/ckanext-geoview#ol4 .
Be welcome to be an early adopter, or wait for its merging into the
official branch, hopefully in the coming weeks.


Le 13 juil. 2017 9:25 AM, "Dythya" <notifications@github.com> a écrit :

The version of OpenLayers looks to be a couple of years old.

Is there any work currently being done around updating the version of
OpenLayers?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ckan/ckanext-geoview/issues/9#issuecomment-314995108>,
or mute the thread

**Comment by dythya** [comment]
Thanks for that.

**Comment by mattfullerton** [comment]
This would appear to be fixed, I see requests to
http://stamen-tiles-b, c, d in the network activity
